"""Core semantic contracts for Dicta."""

from dicta.core.appraise import (
    AppraisalResult,
    ArithmeticDatum,
    CounterIncrementDatum,
    appraise_arithmetic_datum,
    appraise_arithmetic_result,
    appraise_counter_revision_datum,
    appraise_counter_revision_result,
)
from dicta.core.models import (
    Concept,
    Datum,
    Dictum,
    Disparity,
    Inference,
    Outcome,
    Program,
    Purpose,
    Qualification,
    Revision,
    RevisionOperation,
)
from dicta.core.qualification import (
    QualificationStrength,
    asserted,
    checked,
    proved,
    tested,
)
from dicta.core.query import (
    dicta_by_kind,
    dicta_by_qualification_strength,
    dicta_with_tag,
    disparities_by_kind,
    has_dictum_meaning,
    has_dictum_text,
    outcomes_by_kind,
    revisions_by_kind,
)

__all__ = [
    "Concept",
    "Datum",
    "Dictum",
    "Disparity",
    "Inference",
    "Outcome",
    "Program",
    "Purpose",
    "Qualification",
    "QualificationStrength",
    "Revision",
    "RevisionOperation",
    "AppraisalResult",
    "ArithmeticDatum",
    "CounterIncrementDatum",
    "asserted",
    "appraise_arithmetic_datum",
    "appraise_arithmetic_result",
    "appraise_counter_revision_datum",
    "appraise_counter_revision_result",
    "checked",
    "dicta_by_kind",
    "dicta_by_qualification_strength",
    "dicta_with_tag",
    "disparities_by_kind",
    "has_dictum_meaning",
    "has_dictum_text",
    "outcomes_by_kind",
    "proved",
    "revisions_by_kind",
    "tested",
]
